// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/grpc/entry.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_api_grpc_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_entry_proto_rawDescGZIP(), []int{0}
}

func (x *GetEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_api_grpc_entry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_entry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_entry_proto_rawDescGZIP(), []int{1}
}

func (x *GetEntryResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetEntryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_api_grpc_entry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_entry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_entry_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEntryRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_api_grpc_entry_proto protoreflect.FileDescriptor

const file_api_grpc_entry_proto_rawDesc = "" +
	"\n" +
	"\x14api/grpc/entry.proto\x12\x04grpc\x1a\x1bgoogle/protobuf/empty.proto\"!\n" +
	"\x0fGetEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x10GetEntryResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"&\n" +
	"\x12CreateEntryRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xc9\x01\n" +
	"\fEntryService\x12<\n" +
	"\bAddEntry\x12\x18.grpc.CreateEntryRequest\x1a\x16.grpc.GetEntryResponse\x129\n" +
	"\bGetEntry\x12\x15.grpc.GetEntryRequest\x1a\x16.grpc.GetEntryResponse\x12@\n" +
	"\fWatchEntries\x12\x16.google.protobuf.Empty\x1a\x16.grpc.GetEntryResponse0\x01B\x18Z\x16url-shortener/api/grpcb\x06proto3"

var (
	file_api_grpc_entry_proto_rawDescOnce sync.Once
	file_api_grpc_entry_proto_rawDescData []byte
)

func file_api_grpc_entry_proto_rawDescGZIP() []byte {
	file_api_grpc_entry_proto_rawDescOnce.Do(func() {
		file_api_grpc_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_entry_proto_rawDesc), len(file_api_grpc_entry_proto_rawDesc)))
	})
	return file_api_grpc_entry_proto_rawDescData
}

var file_api_grpc_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_grpc_entry_proto_goTypes = []any{
	(*GetEntryRequest)(nil),    // 0: grpc.GetEntryRequest
	(*GetEntryResponse)(nil),   // 1: grpc.GetEntryResponse
	(*CreateEntryRequest)(nil), // 2: grpc.CreateEntryRequest
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_api_grpc_entry_proto_depIdxs = []int32{
	2, // 0: grpc.EntryService.AddEntry:input_type -> grpc.CreateEntryRequest
	0, // 1: grpc.EntryService.GetEntry:input_type -> grpc.GetEntryRequest
	3, // 2: grpc.EntryService.WatchEntries:input_type -> google.protobuf.Empty
	1, // 3: grpc.EntryService.AddEntry:output_type -> grpc.GetEntryResponse
	1, // 4: grpc.EntryService.GetEntry:output_type -> grpc.GetEntryResponse
	1, // 5: grpc.EntryService.WatchEntries:output_type -> grpc.GetEntryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_entry_proto_init() }
func file_api_grpc_entry_proto_init() {
	if File_api_grpc_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_entry_proto_rawDesc), len(file_api_grpc_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_entry_proto_goTypes,
		DependencyIndexes: file_api_grpc_entry_proto_depIdxs,
		MessageInfos:      file_api_grpc_entry_proto_msgTypes,
	}.Build()
	File_api_grpc_entry_proto = out.File
	file_api_grpc_entry_proto_goTypes = nil
	file_api_grpc_entry_proto_depIdxs = nil
}
